서버 Dicom 데이터 TableView 출력: Dicom Image Viewer 개선
shingagyoung/task pull request #11
Opened 2024-05-27 07:43 UTC by shingagyoung

- close #10 

### 요구사항:
1. WWL 기능 추가 (Window width, Window level)
2. Sagittal, coronal view 추가
### 수정 내용:
1. Dicom image viewer로 axial, sagittal, coronal view 확인 할 수 있는 UI 표현
2. Nrrd data를 sagittal, coronal 이미지로 전환
3. WWL 값 변화에 따라 이미지에 반영되도록 수정

| axial | sagittal | coronal |
| --- | --- | --- |
| <img src="https://github.com/shingagyoung/task/assets/168696469/7a8a1499-2ca4-4987-a215-223871d89038" width = 250 height = 450> </img> | <img src="https://github.com/shingagyoung/task/assets/168696469/0548abca-919b-44dc-9f4e-70ff4538ae8d" width = 250 height = 450> </img>| <img src="https://github.com/shingagyoung/task/assets/168696469/ecf6adb7-d799-429d-8b61-13e45702f4d7" width = 250 height = 450> </img> |

2024-05-30 02:38 UTC, shingagyoung commented on Task2/Extensions/NrrdRaw+imageConversion.swift
> +    private func clampAndNormalize(range: Range) throws -> [Int16] {
필요 없는 부분이라 삭제하였습니다. 메소드 만들고 수정하면서 그대로 남겨둔 것 같습니다.

2024-05-31 01:58 UTC, alkee-skia approved these changes

2024-06-03 04:47 UTC, hyunheeskia requested changes
![image](https://github.com/shingagyoung/task/assets/134245511/88ff6b33-ee07-4968-b237-ce77a4b9adb9)

apply 버튼을 누르면 항상 0번째 slice 로 이동합니다.

2024-06-03 06:33 UTC, ChoiSieun1 approved these changes

2024-06-10 04:49 UTC, YunKeonTeck approved these changes

2024-06-11 00:21 UTC, shingagyoung commented
> ![image](https://private-user-images.githubusercontent.com/134245511/335941020-88ff6b33-ee07-4968-b237-ce77a4b9adb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjU0NzksIm5iZiI6MTcxODA2NTE3OSwicGF0aCI6Ii8xMzQyNDU1MTEvMzM1OTQxMDIwLTg4ZmY2YjMzLWVlMDctNDk2OC1iMjM3LWNlNzdhNGI5YWRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwMDE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzM5ODRlNDFiMzRmNTcwNTQwNDc1YWY1YTE3MjFlM2I5YmFhMmRjY2Y2ZWIzZDVmZWE4MGU5MzE3ODBmMDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qvld09RfxTLGUK603cIEhowjll4g7Burk3HKVKqUa6o)
> 
> apply 버튼을 누르면 항상 0번째 slice 로 이동합니다.

첫장부터 보고 싶어하지 않을까 해서 이동하도록 하긴 했는데, 보고 있는 slice를 그대로 유지하는 게 더 나을까요~?

2024-06-11 00:47 UTC, hyunheeskia commented
> > ![image](https://private-user-images.githubusercontent.com/134245511/335941020-88ff6b33-ee07-4968-b237-ce77a4b9adb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjU0NzksIm5iZiI6MTcxODA2NTE3OSwicGF0aCI6Ii8xMzQyNDU1MTEvMzM1OTQxMDIwLTg4ZmY2YjMzLWVlMDctNDk2OC1iMjM3LWNlNzdhNGI5YWRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwMDE5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzM5ODRlNDFiMzRmNTcwNTQwNDc1YWY1YTE3MjFlM2I5YmFhMmRjY2Y2ZWIzZDVmZWE4MGU5MzE3ODBmMDlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qvld09RfxTLGUK603cIEhowjll4g7Burk3HKVKqUa6o)
> > apply 버튼을 누르면 항상 0번째 slice 로 이동합니다.
> 
> 첫장부터 보고 싶어하지 않을까 해서 이동하도록 하긴 했는데, 보고 있는 slice를 그대로 유지하는 게 더 나을까요~?

아하... 의도한 것이었군요..? 저는 버그인줄 알았습니다..
저는 의도한 것이라면 크게 상관 없다고 생각합니다..

2024-06-11 00:48 UTC, hyunheeskia approved these changes

2024-06-11 01:01 UTC, merged