서버 Dicom 데이터 TableView 출력: Dicom Image Viewer 구현
shingagyoung/task pull request #9
Opened 2024-05-17 07:47 UTC by shingagyoung

- close #8 

### 요구사항:
1. Table View에 Dicom image viewer 구현
2. volume file을 읽고 화면에 axial 이미지 띄우기 

### 수정 내용:
1. axial 이미지 출력을 위해 cell에 UIImageView 추가
2. nrrd data를 uint16 type에 맞춰 읽은 후 image로 변환
3. 느린 데이터 로딩 및 이미지 변환 속도 보완을 위해 caching 적용

**<nrrd image 출력 화면>**
<img src = "https://github.com/shingagyoung/task/assets/168696469/c405914c-b819-4d50-8674-97159e700533" width = 400 height = 600> </img>

**<Caching 적용>**
- `Nrrd load`, `UIImage 변환` 부분에서 시간이 많이 소요되는데, 캐시 사용 이후에는 재로딩 시 아래와 같이 소요 시간이 축소되었습니다. 
- 현재 서버에서 불러오는 가장 이미지 수가 많은 nrrd 파일 (511장) 기준
   -  nrrd load: 약 6초 -> 약 2초
   - 이미지 변환: 약 7초 -> 약 0.001초

![스크린샷 2024-05-17 오후 3 00 06](https://github.com/shingagyoung/task/assets/168696469/a19bc7ba-cebe-454a-a343-369cb168006f)
<적용 전>

![스크린샷 2024-05-17 오후 3 08 55](https://github.com/shingagyoung/task/assets/168696469/3b7fe1e5-ab18-4f3c-857b-63fed91c9f76)
<적용 후>

*Nrrd load 부분 캐싱 적용을 위해 NrrdRaw 파일에 캐싱 관련 로직을 추가하였습니다. 혹시 문제가 된다면 별도의 class를 구성하여 해당 부분 빼내도록 하겠습니다.

2024-05-20 00:41 UTC, shingagyoung commented
초기에 network call로 데이터를 확보한 경우에, caching보다는 오히려 동일한 call이 다시 호출되지 않도록 하는 방식이 코드 가독성도 높고 효율적이이라는 판단이 들었습니다. 그에 따라 caching은 일단 적용하지 않는 방향으로 변경하였습니다.

2024-05-20 02:30 UTC, hyunheeskia requested changes

2024-05-20 02:30 UTC, hyunheeskia commented on Task2/Utils/ImageConverter.swift
> +            width: pixelData[0].count,
0 번째 element 에 접근하려면 pixelData 라는 배열이 비어있지 않은지 어딘가에서 검사해주면 좋을 것 같습니다.
기왕이면 함수 시작할 때 하는 게 좋을것같습니다.

2024-05-20 04:53 UTC, alkee-skia requested changes

2024-05-20 04:53 UTC, alkee-skia commented on Task2/Network/NetworkService.swift
> +              let urlString = urlRequest.url?.absoluteString
사용하지 않는 변수로 xcode 에서 warning 나오지 않나요?

2024-05-20 04:53 UTC, alkee-skia commented on Task2/Utils/ImageConverter.swift
> +            var pixelData: [[UInt16]] = []
swift 가 다차원 배열을 지원하고 있지 않기 때문에 이렇게 하신 것 같은데,
[[type]] 이 명확하게 2차원 배열을 나타내지 않기 때문에 (`[ [1, 2], [3], [4,5,6] ]` 과같은 형태도 가능) 차라리 1 차원 배열과 size(width, height) 로 필요한 순간에 필요한 부분을 잘라서 사용하는 방식이 어떨까 합니다. 코드를 보니, 굳이 다차원 배열이어야 할 이유는 없어보이거든요.

2024-05-20 04:53 UTC, alkee-skia commented on Task2/Utils/ImageConverter.swift
> +    static func convertNrrdToImage(from nrrdRaw: NrrdRaw) throws -> [UIImage] {
argument 에 from type 이 있으므로 함수 이름에 from 의 의미(Nrrd)가 중복되어 있을 필요는 없을 것 같습니다.

그리고 static 한 함수만 있는 ImageConverter 보다는 NrrdRaw 나 UIImage(`.init(huValues:)?`) 의 확장 함수는 어떤가요?

2024-05-20 04:53 UTC, alkee-skia commented on Task2/Utils/ImageConverter.swift
> +                let byteLine = readable.readBytes(count: Int(dataSize.x)*MemoryLayout<UInt16>.size).withUnsafeBytes {
UInt16 으로 읽고 있는데.. HU value 의 범위와 UINT16 의 표현범위를 확인해봐주세요

2024-05-20 04:53 UTC, alkee-skia commented on Task2/Utils/ImageConverter.swift
> +        guard let cgImage = CGImage(
pixelData 가 HU value 인 것 같은데(NRRD 에서 그대로 메모리로 올리기만..)
이 값이 어떤 색(색의 값)이 되는지 확인이 필요해 보입니다. 

grayscale 로 내타내는 경우 어느값이 검정색이 되고 어느값이 흰색이 되고, 그리고 그 사이값은 어느정도의 회색이 되는지 확인해봐주세요.

2024-05-20 05:35 UTC, shingagyoung commented on Task2/Network/NetworkService.swift
> +              let urlString = urlRequest.url?.absoluteString
xcode보다 눈이 좋으시네요.. warning은 나오지 않았습니다. cache 적용할 때 key 값으로 쓰려고 생성했던 변수였는데, 현재 사용하지 않으니 없애겠습니다.

2024-05-22 00:37 UTC, shingagyoung commented on Task2/Utils/ImageConverter.swift
> +            var pixelData: [[UInt16]] = []
다차원 배열 형식 대신에 array를 slicing 하여 사용하는 방식으로 변경하였습니다.

2024-05-22 00:39 UTC, shingagyoung commented on Task2/Utils/ImageConverter.swift
> +                let byteLine = readable.readBytes(count: Int(dataSize.x)*MemoryLayout<UInt16>.size).withUnsafeBytes {
HU value는 -1,024~3,071로, 음수 값을 지원하기 위해 type을 Int16으로 변경하였습니다.

2024-05-22 00:51 UTC, shingagyoung commented on Task2/Utils/ImageConverter.swift
> +        guard let cgImage = CGImage(
grayscale은 0은 black, 255은 white이고 그 사이값들이 회색을 나타내는 것으로 알고 있습니다. 해당 부분에 어떤식으로 적용되어야 하는 지 조금 더 살펴보도록 하겠습니다.

2024-05-22 02:32 UTC, ChoiSieun1 commented
<img width="867" alt="image" src="https://github.com/shingagyoung/task/assets/134345288/5d362864-180d-44c3-a9a6-ed8ecbffac8b">
<img width="994" alt="image" src="https://github.com/shingagyoung/task/assets/134345288/ae05f258-6f4c-41bf-952d-ba3fb2e99c58">

studyID 3 의 seriesID 6, 7 과 studyID 1 의 seriesID 1, 2 가 실제 서버와 조금 다른 듯 합니다 (시작 이미지가)
서버 내에서 이미지를 조금 변경하다보면 같은 이미지가 나오긴하네요

그리고 전체적으로 seriesID 가 서버와 다르게 나오네요. 아마 seriesNumber 로 잘못 쓴 듯 합니다

2024-05-22 02:49 UTC, alkee-skia commented on Task2/Utils/ImageConverter.swift
> +        guard let cgImage = CGImage(
> HU value는 -1,024~3,071로, 음수 값을 지원하기 위해 type을 Int16으로 변경하였습니다.

예를들어 몇가지 값만 놓고 보면
HU value 가 -1024, 0, 1024, 2048 일 때 어떤 색을 갖을까요?

2024-05-22 06:18 UTC, shingagyoung commented on Task2/Utils/ImageConverter.swift
> +        guard let cgImage = CGImage(
색상은 
- -1024: 검정색
- 0: 어두운 회색
- 1024: 밝은 회색
- 2048: 흰색에 가까운 색

이 될 거 같습니다. 

GrayScale과는 색상을 나누는 기준에 차이가 있어서, wwl 값을 적용하여 변환해야 할 필요성을 의미하시는 걸까요?

2024-05-22 08:23 UTC, shingagyoung commented
> studyID 3 의 seriesID 6, 7 과 studyID 1 의 seriesID 1, 2 가 실제 서버와 조금 다른 듯 합니다 (시작 이미지가) 서버 내에서 이미지를 조금 변경하다보면 같은 이미지가 나오긴하네요
> 
> 그리고 전체적으로 seriesID 가 서버와 다르게 나오네요. 아마 seriesNumber 로 잘못 쓴 듯 합니다

- seriesID 확인해서 수정하였습니다.
- 이미지 순서는 3D Slicer랑 서버랑 순서가 정반대로 나오는 것 같네요. 어느 곳이 맞는 지 잘 모르지만 현재 3D Slicer하고 일치하긴 합니다. 서버가 맞는 것이라면 순서 변경해야 할 것 같습니다~

2024-05-22 09:08 UTC, alkee-skia commented on Task2/ViewModels/StudySection.swift
> +        let nrrdData = try await NrrdRaw.loadAsync(url)
이렇게 사용했을 때 disk cache 가 되나요? cache 되지 않으면 매 실행마다 처음 로딩이 상당히 오래 걸릴 수 있을 것 같습니다만?

2024-05-22 09:08 UTC, alkee-skia commented on Task2/Views/SeriesTableViewCell.swift
> +                self.loadIndicator.stopAnimating()
fetchDicomImage 가 실패(catch 되는 상황)하면 loadIndicator 의 animation 이 끝나지 않을 것 같네요.

```
Task {
   self.loadIndicator.startAnimating()
   defer { self.loadIndicator.stopAnimating() } 
   do { ...
}
```

와 같은 방식을 고려해보시면 좋겠습니다.

2024-05-22 10:27 UTC, shingagyoung commented on Task2/ViewModels/StudySection.swift
> +        let nrrdData = try await NrrdRaw.loadAsync(url)
UserDefaults로 시도해보니 데이터 크기가 너무 커서, FileManager로 disk cache 적용 해보도록 하겠습니다.

2024-05-23 02:02 UTC, shingagyoung commented on Task2/ViewModels/StudySection.swift
> +        let nrrdData = try await NrrdRaw.loadAsync(url)
FileManager 적용하여 load time은 줄였습니다. Image data를 clamping 하는 작업도 시간이 꽤 소요되어서 여기에도 적용 시도(clamping한 데이터를 disk에 저장) 해보았는데, 저장된 값을 disk에서 읽는 게 오히려 더 시간이 오래 걸렸습니다. 그래서 일단 해당 로직은 현재 적용하지 않았고 더 적절한 방식을 찾아보아야 할 것 같습니다.

2024-05-23 05:15 UTC, alkee-skia requested changes

2024-05-23 05:15 UTC, alkee-skia commented on Task2/Extensions/NrrdRaw+Extensions.swift
> +                            return Int16(255)
max 보다 크면 max 로 return 해야하는 것이 의도된 함수의 동작 같습니다만..?

2024-05-23 05:15 UTC, alkee-skia commented on Task2/Extensions/String+Extensions.swift
> +        guard parts.count >= 4 else { return nil }
3, 4 등 하드코딩으로 너무 한정된 상황에서만 사용되는 함수같아보이네요. 
[lastPathComponent](https://developer.apple.com/documentation/foundation/nsstring/1416528-lastpathcomponent) / [deletingPathExtension](https://developer.apple.com/documentation/foundation/nsstring/1418214-deletingpathextension) 등을 이용할 수도 있었을 것 같습니다?

2024-05-23 05:15 UTC, alkee-skia commented on Task2/ViewModels/StudySection.swift
> +            try JSONEncoder().encode(nrrdData).write(to: directory)
json 으로 저장하시는 이유가 있을까요?

2024-05-23 05:15 UTC, alkee-skia commented on Task2/ViewModels/StudySection.swift
> +    private func getFileDirectory(of data: Series) throws -> URL {
directory 가 아닌 file 의 url 을 반환하는것 같습니다

2024-05-23 09:41 UTC, shingagyoung commented on Task2/ViewModels/StudySection.swift
> +            try JSONEncoder().encode(nrrdData).write(to: directory)
FileManager에 저장할 때 `Data` type으로 저장해야 합니다.
예를 들어서 String의 경우,
```
let fileContents = "abc"
fileContents.data(using: .utf8)?.write(to: filePath)
```
와 같이 data로 변환이 가능하여 바로 저장이 가능합니다. 하지만 `NrrdRaw` type은 전환이 안되어서, 대신 각 struct가 Codable을 준수하게 한 다음 json형태로 변환하여 저장하였습니다~

2024-05-23 09:46 UTC, shingagyoung commented on Task2/Extensions/NrrdRaw+Extensions.swift
> +                            return Int16(255)
..흐릿한 눈이 만들어 낸 실수였습니다.

2024-05-23 12:00 UTC, alkee-skia commented on Task2/ViewModels/StudySection.swift
> +        directory.append(path: "\(series.volumeFilePath.fileName).txt")
`.txt` 로 저장하시는 이유가 있을까요?

2024-05-24 08:16 UTC, shingagyoung commented on Task2/ViewModels/StudySection.swift
> +            try JSONEncoder().encode(nrrdData).write(to: directory)
`Data(contentsOf: serverUrl)`을 이용해서 초기 로드 시 `.nrrd`로 저장하고 다운로드 된 파일을 `NrrdRaw.loadAsync(cacheUrl)` 로 읽도록 하였습니다.

2024-05-24 08:54 UTC, alkee-skia approved these changes

2024-05-27 00:55 UTC, hyunheeskia commented on Task2/Network/NetworkService.swift
> +              let urlString = urlRequest.url?.absoluteString
없애주세요~

2024-05-27 02:00 UTC, shingagyoung commented on Task2/Network/NetworkService.swift
> +              let urlString = urlRequest.url?.absoluteString
@hyunheeskia 삭제가 안되었었군요..삭제 하였습니다

2024-05-27 02:10 UTC, hyunheeskia approved these changes

2024-05-27 02:21 UTC, ChoiSieun1 commented
> > studyID 3 의 seriesID 6, 7 과 studyID 1 의 seriesID 1, 2 가 실제 서버와 조금 다른 듯 합니다 (시작 이미지가) 서버 내에서 이미지를 조금 변경하다보면 같은 이미지가 나오긴하네요
> > 그리고 전체적으로 seriesID 가 서버와 다르게 나오네요. 아마 seriesNumber 로 잘못 쓴 듯 합니다
> 
> * seriesID 확인해서 수정하였습니다.
> * 이미지 순서가 3D Slicer랑 서버랑 정반대로 나오는 것 같네요. 어느 곳이 맞는 지 잘 모르지만 현재 3D Slicer하고 일치하긴 합니다. 서버가 맞는 것이라면 순서 변경해야 할 것 같습니다~

서로 방식이 달라서 나온 결과인 것 같네요.
이정도까지만 해도 될 듯 합니다~

2024-05-27 02:21 UTC, ChoiSieun1 approved these changes

2024-05-27 05:45 UTC, YunKeonTeck approved these changes

2024-05-27 06:31 UTC, merged